// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.


// TODO(wheatman) think about making this autogenerated

// I wanted to pass UINFO through cgo -cdefs, but it turns all #defines into
// enums, which can only be 32-bit
#ifdef _64BIT
//#define UINFO 0x00007f7fffc00000
static const uint64 UINFO = 0x00007f7fffc00000ULL;
#else
//#define UINFO 0x7f800000
static const uint32 UINFO = 0x7f800000UL;
#endif

#define MIN(a, b)	((a < b) ? a : b)
#define MAX(a, b)	((a > b) ? a : b)

#define __procinfo (*(ProcinfoType*)UINFO)
