// This file has been manually generated by trying to build particular GO
// packages and realizing that we don't yet have definitions for particular
// errors or signals as originally required by the linux port we derive
// outselves from. As we continue porting the contants in here will start to
// disappear. The contants are copied out of zerrors_linux_amd64.go

package syscall

const (
	PR_SET_PDEATHSIG    = 0x1
	PTRACE_TRACEME      = 0x0
	SIOCGIFFLAGS        = 0x8913
	SIOCSIFFLAGS        = 0x8914
	NLMSG_ALIGNTO       = 0x4
	RTA_ALIGNTO         = 0x4
	NLMSG_HDRLEN        = 0x10
	NLM_F_DUMP          = 0x300
	NLM_F_REQUEST       = 0x1
	NETLINK_ROUTE       = 0x0
	NLMSG_DONE          = 0x3
	NLMSG_ERROR         = 0x2
	RTM_NEWLINK         = 0x10
	RTM_DELLINK         = 0x11
	RTM_NEWADDR         = 0x14
	RTM_DELADDR         = 0x15
	RTM_NEWROUTE        = 0x18
	RTM_DELROUTE        = 0x19
	PTRACE_PEEKTEXT     = 0x1
	PTRACE_PEEKDATA     = 0x2
	PTRACE_POKETEXT     = 0x4
	PTRACE_POKEDATA     = 0x5
	PTRACE_GETREGS      = 0xc
	PTRACE_SETREGS      = 0xd
	PTRACE_SETOPTIONS   = 0x4200
	PTRACE_GETEVENTMSG  = 0x4201
	PTRACE_CONT         = 0x7
	PTRACE_SYSCALL      = 0x18
	PTRACE_SINGLESTEP   = 0x9
	PTRACE_ATTACH       = 0x10
	PTRACE_DETACH       = 0x11
	LINUX_REBOOT_MAGIC1 = 0xfee1dead
	LINUX_REBOOT_MAGIC2 = 0x28121969
	RTM_GETLINK         = 0x12
	RTM_GETADDR         = 0x16
	TCIFLUSH            = 0x0
	TCIOFLUSH           = 0x2
	TCOFLUSH            = 0x1
)
